version: "3"

services:

  postgres:
    image: postgres
    restart: always

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
    
    volumes:
      - ./pgdata:/var/lib/postgresql/data

    ports: 
      - '5432:5432'
